"""
formatter.py
------------
Output formatter: convert audit findings ke JSON file & Markdown report.
"""

import json
import os
from datetime import datetime
from typing import Dict


def save_json_report(report: Dict, output_dir: str = "output") -> str:
    """
    Save audit report sebagai JSON file.
    
    Args:
        report: dict dari audit_contract()
        output_dir: folder output
    
    Returns:
        path ke file JSON yang disave
    """
    
    # TODO 1: Bikin output directory kalau belum ada
    # Hint: os.makedirs(output_dir, exist_ok=True)
    os.makedirs(output_dir, exist_ok=True)
    
    
    # TODO 2: Generate filename dari nama contract + timestamp
    # Hint:
    #   - contract name: os.path.basename(report["contract"]).replace(".sol", "")
    #   - timestamp: datetime.now().strftime("%Y%m%d_%H%M%S")
    #   - filename: f"{contract_name}_{timestamp}.json"
    #   - filepath: os.path.join(output_dir, filename)
    contract_name = os.path.basename(report["contract"]).replace(".sol", "")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{contract_name}_{timestamp}.json"
    filepath = os.path.join(output_dir, filename)
    
    # TODO 3: Write JSON ke file
    # Hint:
    #   - with open(filepath, "w") as f:
    #   -     json.dump(report, f, indent=2)
    #   - return filepath
    with open(filepath, "w") as f:
        json.dump(report, f, indent=2)
        
    return filepath


def save_markdown_report(report: Dict, output_dir: str = "output") -> str:
    """
    Save audit report sebagai Markdown file.
    
    Args:
        report: dict dari audit_contract()
        output_dir: folder output
    
    Returns:
        path ke file Markdown yang disave
    """
    
    # TODO 4: Bikin output directory
    os.makedirs(output_dir, exist_ok=True)
    
    # TODO 5: Generate filename (sama pattern kayak JSON, tapi .md)
    contract_name = os.path.basename(report["contract"]).replace(".sol", "")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{contract_name}_{timestamp}.md"
    filepath = os.path.join(output_dir, filename)
    
    # TODO 6: Build markdown content string
    # Hint: pake f-string multi-line, contoh structure:
    #
    # # Security Audit Report
    # **Contract:** {report["contract"]}
    # **Date:** {timestamp}
    # **Total Findings:** {report["total_findings"]}
    # - Slither: {report["slither_count"]}
    # - Gemini: {report["gemini_count"]}
    #
    # ---
    #
    # ## Findings
    #
    # ### [1] [SLITHER] REENTRANCY-ETH
    # - **Impact:** High
    # - **Confidence:** Medium
    # - **Lines:** 11-19
    # - **Description:** ...
    date_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
 
    md = f"# Security Audit Report\n\n"
    md += f"**Contract:** `{report['contract']}`\n\n"
    md += f"**Date:** {date_str}\n\n"
    md += f"**Total Findings:** {report['total_findings']}\n\n"
    md += f"| Source | Count |\n"
    md += f"|--------|-------|\n"
    md += f"| Slither | {report['slither_count']} |\n"
    md += f"| Gemini | {report['gemini_count']} |\n\n"
    md += f"---\n\n"
    md += f"## Findings\n\n"
    
    
    # TODO 7: Loop setiap finding, tambahin ke markdown string
    # Hint:
    #   - for i, finding in enumerate(report["findings"], start=1):
    #   -     md += f"### [{i}] [{finding['source'].upper()}] {finding['check'].upper()}\n"
    #   -     md += f"- **Impact:** {finding['impact']}\n"
    #   -     ... dst
    for i, finding in enumerate(report["findings"], start=1):
        source = finding["source"].upper()
        check = finding["check"].upper()
 
        md += f"### [{i}] [{source}] {check}\n\n"
        md += f"- **Impact:** {finding['impact']}\n"
        md += f"- **Confidence:** {finding['confidence']}\n"
        md += f"- **Lines:** {finding['lines']}\n"
        md += f"- **Description:** {finding['description']}\n\n"

    # footer
    md += f"---\n\n"
    md += f"*Generated by Solidity AI Auditor*\n"

    
    # TODO 8: Write markdown ke file
    # Hint: sama kayak JSON, tapi pake f.write(md) bukan json.dump
    # Return filepath
    with open(filepath, "w") as f:
        f.write(md)
 
    return filepath